name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Windows Docker image to Docker Hub
    runs-on: windows-2019
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: powerCLI - Build and push
        uses: docker/build-push-action@v2
        with:
          context: /powerCLI
          pull: true
          push: false
          cache-from: type=registry,ref=jpatigny/powercli:latest
          cache-to: type=inline
          tags: jpatigny/powercli:latest
