name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    name: "[ Build ]"
    runs-on: windows-2022
    strategy:
      fail-fast: False
      matrix:
        application: [""]
        app_version: [""]
        os_version:  [""]
        os_type: [""]
        include:
          - application: alertmanager
            app_version: 0.24.0
            os_version: ['ltsc2022','1809']
            os_type: ['nanoserver','windowsservercore']
          # - application: blackbox_exporter
          #   os_version: ['ltsc2022','1809']
          #   os_type: ['nanoserver','windowsservercore']
          # - application: checkov
          #   os_version: ['ltsc2022','1809']
          #   os_type: ['nanoserver','windowsservercore']
          # - application: chocolatey
          #   os_version: ['ltsc2022','1809']
          #   os_type: windowsservercore
          # - application: grafana
          #   os_version: ['ltsc2022','1809']
          #   os_type: ['nanoserver','windowsservercore']
          # - application: nexus
          #   os_version: ['ltsc2022','1809']
          #   os_type: ['nanoserver','windowsservercore']
          # - application: powercli
          #   os_version: ['ltsc2022','1809']
          #   os_type: windowsservercore
          # - application: prometheus
          #   os_version: ['ltsc2022','1809']
          #   os_type: ['nanoserver','windowsservercore']
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: ${{ matrix.application }} ${{ matrix.app_version }} ${{ matrix.os_type }} ${{ matrix.os_version }}
        shell: pwsh
        run: |
          cd $env:application
          docker build --isolation=hyperv --build-arg OS_TYPE=$($env:os_type) --build-arg OS_VERSION=$($env:os_version) --build-arg VERSION=$($env:app_version) . -t $($env:GITHUB_REPOSITORY_OWNER)/$($env:application):$($env:app_version)-$($env:os_type)-$($env:os_version)
          docker push $($env:GITHUB_REPOSITORY_OWNER)/$($env:application):$($env:app_version)-$($env:os_type)-$($env:os_version)
        env:
          application: ${{ matrix.application }}
          app_version: ${{ matrix.app_version }}
          os_type: ${{ matrix.os_type }}
          os_version: ${{ matrix.os_version }}

