name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  #   get-all-packages:
  #     runs-on: ubuntu-latest
  #     name: "Get package list"
  #     outputs:
  #       packages: join(${{ steps.list.outputs.packages }}, 
  #     steps:
  #       -
  #         name: Checkout code
  #         uses: actions/checkout@v2

  #       - id: list
  #         shell: pwsh
  #         run: |
  #           tree $pwd
  #           $packages = (Get-ChildItem -Directory -Exclude '.github').Name | Sort-Object
  #           $packages
  #           Write-Host "::set-output name=packages::$packages"

  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.3

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  # build:
  #   needs: get-changed-packages
  #   name: "Build"
  #   runs-on: windows-2022
  #   strategy:
  #     matrix:
  #       package: {{ needs.get-changed-packages.outputs.packages }}
  #       dockerfile: [dockerfile.nanoserver]
  #       os_type: [nanoserver]
  #       os_version: [1809, ltsc2022]
  #   steps:
  #     -
  #       name: Checkout code
  #       uses: actions/checkout@v2
    
  #     - 
  #       name: "Check dockerfile.nano existence"
  #       id: check_files
  #       uses: andstor/file-existence-action@v1
  #       with:
  #         files: "${{ matrix.package }}/${{ matrix.dockerfile }}"
      # - 
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   with:
      #     image: $GITHUB_REPOSITORY_OWNER/${{ matrix.package }}
      #     buildArgs: OS_TYPE=${{ matrix.os_type }}, OS_VERSION=${{ matrix.os_version }}
      #     tags: ${{ matrix.os_type }}-${{ matrix.os_version }}
      #     registry: docker.io
      #     dockerfile: ${{ matrix.package }}/${{ matrix.dockerfile }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

