name: test-modif-files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: check
        uses: tj-actions/changed-files@v29.0.7
      - name: List all changed files
        run: |
          $files = ("${{ steps.check.outputs.all_changed_files }}").split(' ')
          foreach ($file in $files) {
           Write-Host $file
          }
      - if: steps.check.outputs.any_changed == 'true'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: steps.check.outputs.any_changed == 'true'
        name: build ${{ matrix.os }}
        shell: pwsh
        run: |
             $files = ("${{ steps.check.outputs.all_changed_files }}").split(' ')
             $packages = @()
             foreach($file in $files) {
               $package = $file.split('/') | Select -First 1
               $package
               if ($package -notmatch '.github') {
                $packages += $package 
               }
               else {
                 Write-Host "package is .github folder. stopping."
               }
             }
             $packages