name: test-modif-files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: check changes files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          json: "true"
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
  build:
    needs: changed-files
    strategy:
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      -
        if: needs.changed-files-specific.outputs.files == ''
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        if: needs.changed-files-specific.outputs.files == ''
        name: build ${{ matrix.os }}
        shell: pwsh
        run: |
             dir $({{ needs.changed-files-specific.outputs.files }} | ConvertFrom-Json)